package com.bayarsahintekin.matchscores.ui.theme

import androidx.compose.ui.graphics.Color
import com.bayarsahintekin.matchscores.util.toColor

val msLightPrimary = Color(0xFF825500)
val msLightOnPrimary = Color(0xFFFFFFFF)
val msLightPrimaryContainer = Color(0xFFFFDDAE)
val msLightOnPrimaryContainer = Color(0xFF2A1800)
val msLightSecondary = Color(0xFF6F5B40)
val msLightOnSecondary = Color(0xFFFFFFFF)
val msLightSecondaryContainer = Color(0xFFFADEBC)
val msLightOnSecondaryContainer = Color(0xFF271904)
val msLightTertiary = Color(0xFF516440)
val msLightOnTertiary = Color(0xFFFFFFFF)
val msLightTertiaryContainer = Color(0xFFD3EABC)
val msLightOnTertiaryContainer = Color(0xFF102004)
val msLightError = Color(0xFFBA1B1B)
val msLightErrorContainer = Color(0xFFFFDAD4)
val msLightOnError = Color(0xFFFFFFFF)
val msLightOnErrorContainer = Color(0xFF410001)
val msLightBackground = Color(0xFFFCFCFC)
val msLightOnBackground = Color(0xFF1F1B16)
val msLightSurface = Color(0xFFFCFCFC)
val msLightOnSurface = Color(0xFF1F1B16)
val msLightSurfaceVariant = Color(0xFFF0E0CF)
val msLightOnSurfaceVariant = Color(0xFF4F4539)
val msLightOutline = Color(0xFF817567)
val msLightInverseOnSurface = Color(0xFFF9EFE6)
val msLightInverseSurface = Color(0xFF34302A)
val msLightPrimaryInverse = Color(0xFFFFB945)

val msDarkPrimary = Color(0xFFFFB945)
val msDarkOnPrimary = Color(0xFF452B00)
val msDarkPrimaryContainer = Color(0xFF624000)
val msDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val msDarkSecondary = Color(0xFFDDC3A2)
val msDarkOnSecondary = Color(0xFF3E2E16)
val msDarkSecondaryContainer = Color(0xFF56442B)
val msDarkOnSecondaryContainer = Color(0xFFFADEBC)
val msDarkTertiary = Color(0xFFB8CEA2)
val msDarkOnTertiary = Color(0xFF243516)
val msDarkTertiaryContainer = Color(0xFF3A4C2B)
val msDarkOnTertiaryContainer = Color(0xFFD3EABC)
val msDarkError = Color(0xFFFFB4A9)
val msDarkErrorContainer = Color(0xFF930006)
val msDarkOnError = Color(0xFF680003)
val msDarkOnErrorContainer = Color(0xFFFFDAD4)
val msDarkBackground = Color(0xFF1F1B16)
val msDarkOnBackground = Color(0xFFEAE1D9)
val msDarkSurface = Color(0xFF1F1B16)
val msDarkOnSurface = Color(0xFFEAE1D9)
val msDarkSurfaceVariant = Color(0xFF4F4539)
val msDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val msDarkOutline = Color(0xFF9C8F80)
val msDarkInverseOnSurface = Color(0xFF32281A)
val msDarkInverseSurface = Color(0xFFEAE1D9)
val msDarkPrimaryInverse = Color(0xFF624000)


val BlueGradient = "#5edeef".toColor()
val YellowGradient = "#dce956".toColor()
val PinkGradient = "#e98fc0".toColor()
val TeamsBG = "#f5e5d7".toColor()

val G1 = "#5A585A".toColor()
val G2 = "#090947".toColor()

val msOrange = "#FFA726".toColor()
val msPurple = "#B388FF".toColor()