# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

default_platform(:android)

platform(:android) do
 lane :build_debug_apk do
   gradle(
     task: 'assembleDebug'
   )
 end
 lane :deploy_to_firebase do
    value = firebase_app_distribution(
     app: "1:173895711456:android:ab6ef0ede01fcfef14ee85",
     firebase_cli_token: "1//09M6ksX9WARImCgYIARAAGAkSNwF-L9Irpp5Q9ik-b2wtBHOAoBNeGVAox-qQRiXY49_w7MtFJtHGOjth1Lq3cyrsnts_8IRq7SQ",
     android_artifact_type: "APK",
     android_artifact_path: "presentation/build/outputs/apk/debug/presentation-debug.apk",
     release_notes: "UI developments finalizedddd",
     groups: "dev-group",
     debug: false
    )
  end
end