name: MSWorkflow
on:
  pull_request:
    branches: [main]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
            ruby-version: '2.7'
      - run: |
              yarn global add firebase-tools
              echo "::add-path::$(yarn global bin)"

      - run: bundle install

      - run: bundle exec fastlane android firebase_distribution
        env:
            FIREBASE_CLI_TOKEN: "1//09M6ksX9WARImCgYIARAAGAkSNwF-L9Irpp5Q9ik-b2wtBHOAoBNeGVAox-qQRiXY49_w7MtFJtHGOjth1Lq3cyrsnts_8IRq7SQ"
            FIREBASE_APP_ID: "1:173895711456:android:ab6ef0ede01fcfef14ee85"
