name: MSWorkflow
on:
  pull_request:
    branches: [main]
  push:
    branches: [ main ]

jobs:
  gradle-validation:
    name: Gradle Wrapper
    runs-on: [ self-hosted ]
    steps:

      # Checkout current repository

      - uses: actions/checkout@v2

      # Validate Wrapper

      - uses: gradle/wrapper-validation-action@v1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - run:  ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: MatchScores.apk
          path: app/build/outputs/apk/app-debug.apk