name: MSWorkflow
on:
  pull_request:
    branches: [main]
  push:
    branches: [ main ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request  analysis

      - name: 'Use Node.js 18.x'
        uses: actions/setup-node@v2
        with:
            node-version: 18.x

      - name: 'Install dependencies'
        run: npm ci
        working-directory: JS/jest

      - name: 'Run tests'
        run: npm test
        working-directory: JS/jest

      - name: 'Archive coverage data # Archive data for using by Qodana'
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage-data
          path: JS/jest/.qodana/code-coverage

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "-i,JS/jest,--linter,jetbrains/qodana-js:2023.3-eap"
          pr-mode: false



  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - uses: gradle/wrapper-validation-action@v1
      - run:  ./gradlew build

      - run: |
         git config --global user.email "bayarsahintekin0@github.com"
         git config --global user.name "bayarsahintekin0"
